[package]
name    = "ikk-core"
version = "0.8.8"
edition = "2024"

[dependencies]
serde       = { workspace = true }
serde_json  = { workspace = true }
toml        = { workspace = true }
sha2        = { workspace = true }
hex         = { workspace = true }
tokio       = { workspace = true }
reqwest     = { workspace = true }
tracing     = { workspace = true }
thiserror   = { workspace = true }
anyhow      = { workspace = true }
dirs        = { workspace = true }
url         = { workspace = true }
async-trait = { workspace = true }
indicatif   = { workspace = true }
futures     = { workspace = true }
flate2      = "1"
tar         = "0.4"
zip         = "8"
xz2         = { version = "0.1", features = ["static"] }
fs2 = "0.4.3"
jiff = "0.2.35"

[features]
default   = []
telemetry = []
sandbox   = []
sigstore  = []
