[package]
name    = "ikk-cli"
version = "0.8.3"
edition = "2024"

[[bin]]
name = "ikk"
path = "src/main.rs"

[dependencies]
ikk-core           = { path = "../ikk-core" }
clap               = { workspace = true }
tokio              = { workspace = true }
anyhow             = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
reqwest            = { workspace = true }
url.workspace = true
